### ISSUE TITLE
Review Accessibility Statement

### ISSUE THREAD

**Issue by gandro** [RustFestEU/paris.rustfest.eu#24]
The current accessibility statement contains the following statements:

> We provide non-gendered toilets.

We should double check with the venue if we can implement this (I don't expect this to be a problem, but we should ask).

> Sadly, only guide animals are allowed at the venue.

This was the case for Zurich. We need to check with the Paris venue regarding animals (e.g. especially if also non-guide animals are allowed on site).

**Comment by loganmzz** [comment]
As member of association about guide dogs, I can say they can't be forbidden ; it's in the French law.
