### ISSUE TITLE
Add Guillaume

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/paris.rustfest.eu#26]
Add @GuillaumeGomez to team.

(Repeat this for both `paris.rustfest.eu` and `blog.rustfest.eu`)

1. Create a file in `_people/$NICK.md` which is based off https://raw.githubusercontent.com/RustFestEU/paris.rustfest.eu/gh-pages/_people/_schema.md
2. Add a nice image of yourself to `assets/organizers/$NICK.png`
3. Check it with `jekyll serve`
4. Make a PR.

**Comment by GuillaumeGomez** [comment]
I didn't find anything on `blog.rustfest.eu`. What am I suppose to update in there?

**Comment by gandro** [comment]
It looks like blog.rustfest.eu is still using the old format. The important file is here: https://github.com/RustFestEU/blog.rustfest.eu/blob/gh-pages/_data/team.yml
