### ISSUE TITLE
Add Geoffroy

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/paris.rustfest.eu#28]
Add @Geal  to team.

(Repeat this for both `paris.rustfest.eu` and `blog.rustfest.eu`)

1. Create a file in `_people/$NICK.md` which is based off https://raw.githubusercontent.com/RustFestEU/paris.rustfest.eu/gh-pages/_people/_schema.md
2. Add a nice image of yourself to `assets/organizers/$NICK.png`
3. Check it with `jekyll serve`
4. Make a PR.

**Comment by dns2utf8** [comment]
Ping
