### ISSUE TITLE
Paris domain mapping

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/paris.rustfest.eu#4]
Map the DNS `paris.rustfest.eu` domain to this repo's github pages.

**Comment by badboy** [comment]
```
% host paris.rustfest.eu
paris.rustfest.eu is an alias for rustfesteu.github.io.
```

Done. Propagating now. Once we have proper content on there I can do the redirect from `(www.)rustfest.eu`

**Comment by Hoverbear** [comment]
@badboy Thank youuuuuu <3

**Comment by dns2utf8** [comment]
That would be great. Or we could host the content elsewhere with TLS support.

**Comment by Hoverbear** [comment]
I removed several comments from @dns2utf8 and @badboy about TLS support as they should be part of a different ticket. Thanks :)
